# Generated by Django 4.2 on 2023-04-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sedan_cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sedan_car',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='imagesSEDAN/'),
        ),
    ]
